spring.application.name=ms-zoonoses-animal

server.port=0

#Eureka disovery Properties
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8082/eureka
eureka.instance.instance-id=${spring.application.name}:${radom.int[1,5]}

#Resilience4j Properties
#tamanho da janela, tipo da janeja, numero minimo de chamadas, duração minima de espera qdo aberto
